"""add_foreign_key_presentations_user_id

Revision ID: d2e3839ae53d
Revises: c1b5572ed944
Create Date: 2026-06-27 17:55:33.547076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2e3839ae53d'
down_revision: Union[str, Sequence[str], None] = 'c1b5572ed944'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'presentations', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'presentations', type_='foreignkey')
    # ### end Alembic commands ###
